---
- name: Deploy To Tomcat
  hosts: web
  become: yes
  tasks:
   - name: Copy war file to tomcat
     copy:
       src: "/var/snap/jenkins/4874/workspace/Maven_CICD/target/Web1bi22cs064.war"
       dest: "/opt/tomcat/webapps/Web1bi22cs064.war"
       remote_src: no
   - name: Restart Tomcat
     systemd:
       name: tomcat
       state: restarted
